version: '3.8'

services:
  pastebin-api:
    build:
      context: ./pastebin-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - pastebin-api-data:/app/data
    networks:
      - pastebin-network

  pastebin-frontend:
    build:
      context: ./pastebin-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://pastebin-api:8080
    networks:
      - pastebin-network

volumes:
  pastebin-api-data:

networks:
  pastebin-network:
    driver: bridge
