version: '3'

tasks:
  build-be: 
    cmds: 
      - docker build -f Pastebin/Dockerfile -t pastebin .
    silent: false

  build-fe:
    cmds: 
      - docker build -f ui/Dockerfile -t pastebin-ui .
    silent: false

  mongo:
    cmds:
      - |-
        docker run -d --name mongodb \
        -p 27017:27017 \
        -v mongo_data:/data/db \
        -e MONGO_INITDB_ROOT_USERNAME=admin \
        -e MONGO_INITDB_ROOT_PASSWORD=adminpass \
        mongo:latest
    silent: false

  be:
    cmds:
      - docker run -d -p 5000:5000 pastebin
    silent: false

  fe:
    cmds:
      - docker run -d -p 8080:8080 pastebin-ui
    silent: false

  default:
    cmds:
      - task: build-be
      - task: build-fe
      - task: be
      - task: fe
      - task: mongo

    silent: false

  rerun:
    cmds:
      - task: be
      - task: fe

    silent: false
